server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testmall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    # redis服务器地址
    host: localhost
    # redis数据库索引（默认为0）
    database: 0
    # redis服务器连接端口
    port: 6379
    # redis 服务器连接密码 默认为空
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #  连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 3000ms


# 自定义 redis key
redis:
  # 自定义 redis key
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      #验证码超期时间
      authCode: 120

#自定义字段
jwt:
  secret: mySecret
  # jwt超期限时间 60*60*24
  expiration: 604800
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT负载中拿到开头
  tokenHead: Bearer

#mybatis
mybatis:
  #mapper 映射文件地址
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:com/**/mapper/*.xml



